# Generated by Django 4.1.3 on 2022-11-20 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('scooter_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('coordinate_x', models.IntegerField(default=0)),
                ('coordinate_y', models.IntegerField(default=0)),
                ('state_of_charge', models.IntegerField(default=0)),
                ('current_earnings', models.DecimalField(decimal_places=10, default=0.0, max_digits=10)),
                ('driven_distance', models.DecimalField(decimal_places=10, default=0.0, max_digits=10)),
                ('current_ride_status', models.BooleanField(default=False)),
            ],
        ),
    ]
