# Generated by Django 4.1.3 on 2022-11-21 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('company_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('cost_per_kilometer', models.DecimalField(decimal_places=10, default=0.0, max_digits=10)),
                ('street', models.CharField(max_length=200)),
                ('house_number', models.IntegerField()),
                ('post_code', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
            ],
        ),
    ]
