# Generated by Django 4.1.3 on 2022-11-21 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter_app', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charging_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('station_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('coordinate_x', models.IntegerField(default=0)),
                ('coordinate_y', models.IntegerField(default=0)),
                ('capacity', models.IntegerField()),
                ('used_loading_places', models.IntegerField()),
            ],
        ),
    ]
