# Generated by Django 4.1.3 on 2022-12-06 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter_app', '0003_charging_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('user_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('mode', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('postalcode', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('pw', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='scooter',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charging_station',
            name='coordinate_x',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='charging_station',
            name='coordinate_y',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='coordinate_x',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='coordinate_y',
            field=models.IntegerField(default=-1),
        ),
    ]
