# Generated by Django 4.1.3 on 2023-01-12 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scooter_app', '0007_rename_post_code_company_postalcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charging_station',
            old_name='coordinate_x',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='charging_station',
            old_name='coordinate_y',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='scooter',
            old_name='coordinate_x',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='scooter',
            old_name='coordinate_y',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
    ]
