# Generated by Django 4.1.3 on 2023-01-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter_app', '0008_rename_coordinate_x_charging_station_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='latitude',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='longitude',
            field=models.FloatField(default=-1),
        ),
    ]
