# Generated by Django 4.1.3 on 2023-01-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter_app', '0009_alter_scooter_latitude_alter_scooter_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='charging_station',
            name='company_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charging_station',
            name='latitude',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='charging_station',
            name='longitude',
            field=models.FloatField(default=-1),
        ),
    ]
