# Generated by Django 4.1.3 on 2023-01-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter_app', '0010_charging_station_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='state_of_charge',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
