# Generated by Django 4.1.3 on 2023-01-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter_app', '0011_alter_scooter_state_of_charge_alter_scooter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='income',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=10),
        ),
    ]
